version: '2'
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    tty: true
    ports:
        - 8443:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/ #optional
      
    volumes:
      - ../v6:/config
    restart: unless-stopped