openapi: 3.0.0
info:
  title: UserManager
  description: API para controlar contas e grupos de usuários
  version: 0.0.1
  termsOfService: http://localhost:3031s
  contact:
    name: USER Manangers
    email: fslab@fslab.dev
    url: fslab.dev
  license:
    name: 'Lincença: GPLv3'
    url: https://www.gnu.org/licenses/gpl-3.0.html
tags:
  - name: Grupos
    description: Operações para grupos
externalDocs:
  description: Documentação detalhada
  url: https://docs.api.fslab.dev
servers:
  - url: http://localhost:3031
    description: API de produção do FSLAB
  - url: http://localhost:3031
    description: API de teste do FSLAB
paths:
  /grupos:
    get:
      summary: Recupera todos os grupos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grupos'
        '404':
          description: Nenhum grupo encontrado
          content:
            application/json:
              example: Not Found
    post:
      summary: Cria um novo grupo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
                ativo:
                  type: boolean
      responses:
        '201':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grupo'
        '404':
          description: Grupo não encontrado
          content:
            application/json:
              example: Not Found
        '409':
          description: Grupo já existe
          content:
            application/json:
              example: Conflict    

  /grupos/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
        
    get:
      summary: Recupera um grupo pelo ID
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grupo'
        '404':
          description: Grupo não encontrado
          content:
            application/json:
              example: Not Found

    put:
      summary: Atualiza um grupo pelo ID
      requestBody:
        description: Atualiza um grupo pelo ID
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/grupo_put'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grupo'
        '204':
          description: Grupo não encontrado
          content:
            application/json:
              example: No Content
        '404':
          description: Grupo não encontrado
          content:
            application/json:
              example: Not Found
    
    delete:
      summary: Apagar um grupo pelo ID
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example: Success
        '404':
          description: Grupo não encontrado
          content:
            application/json:
              example: Not Found              

security:
  - auth: []
  
components:
  schemas:
    grupo:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string

    grupos:
      type: array
      items:
        $ref: '#/components/schemas/grupo'
    
    grupo_put:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
          
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT